#pragma once

#define MESSAGE_SIZE 1504
#define MAXIMUM_MESSAGE_SIZE Packet::DATA_SIZE * 50

#define INTERMEDIARY_BUFFER_ITEMS 100
#define INTERMEDIARY_BUFFER_SIZE MESSAGE_SIZE * INTERMEDIARY_BUFFER_ITEMS

#define ACK_TIMEOUT 20000
#define HANDSHAKE_TIMEOUT 20000
#define MAX_PACKET_TRIES 5