#pragma once

#define INTERMEDIARY_BUFFER_ITEMS 100
#define MAX_ENQUEUED_TRANSMISSIONS 100

#define ACK_TIMEOUT 5000
#define HANDSHAKE_TIMEOUT 5000
#define MAX_PACKET_TRIES 3

#define MAX_HEARTBEAT_TRIES 6